services:
  - type: web
    name: rifas-web
    env: node
    rootDir: .
    buildCommand: cd src/screens/web && npm install && npm run build
    startCommand: cd src/screens/web && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
