services:
  - type: web
    name: rifas-web
    env: node
    rootDir: src/screens/web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
        sync: false
      - key: NODE_VERSION
        value: '20'

