services:
  - type: web
    name: rifas-web
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://backednnuevo.onrender.com
