services:
  - type: web
    name: mega-rifas
    env: node
    rootDir: .
    buildCommand: npm ci --include=dev && npm install --no-save lightningcss-linux-x64-gnu@1.30.2 @tailwindcss/oxide-linux-x64-gnu@4.1.18 && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
        sync: false
